### ISSUE TITLE
原神黄历图片字体错位

### ISSUE THREAD

**Issue by Mateoust** [H-K-Y/Genshin_Impact_bot#10]
日期这里错位了,有点奇怪
用的是go-cqhttp v1.0.0-alpha1
另外有黄历了，大佬是否可以加一个每日素材的提醒呢？感觉挺实用的
![1](https://user-images.githubusercontent.com/46558043/112722957-39329b80-8f47-11eb-9e4f-5a5893670ed5.png)
![2](https://user-images.githubusercontent.com/46558043/112722958-3a63c880-8f47-11eb-9f1a-4944463a7703.png)

**Comment by H-K-Y** [comment]
字体错位的问题你需要把python的Pillow库升级到8.0.0以上
每日材料提醒我明天写一下吧

**Comment by Mateoust** [comment]
> 字体错位的问题你需要把python的Pillow库升级到8.0.0以上
> 每日材料提醒我明天写一下吧

感谢，我的Pillow是6.2.2的。升级后解决了，每日材料提醒麻烦大佬了
