### ISSUE TITLE
大佬，请问大地图还更新吗

### ISSUE THREAD

**Issue by Juenia** [H-K-Y/Genshin_Impact_bot#103]
新的大地图数据，米游社大地图好像把层岩这些地图的资源(怪物)筛选给分开了，导致资源没办法正常查到了

**Comment by Wansn-w** [comment]
唔 事实上渊下宫，甚至金苹果群岛的时候就分开了....关于多个维度这个在和小伙伴们讨论了😂

不久应该就可以搞好

**Comment by Juenia** [comment]
> 唔 事实上渊下宫，甚至金苹果群岛的时候就分开了....关于多个维度这个在和小伙伴们讨论了😂
> 
> 不久应该就可以搞好

好的，谢谢大佬！
