### ISSUE TITLE
圣遗物收集问题

### ISSUE THREAD

**Issue by chingkingm** [H-K-Y/Genshin_Impact_bot#11]
1.雪山副本掉落的两套圣遗物，冰套名字不对，水套图片和名字都不对。
2.没有岩本。

**Comment by H-K-Y** [comment]
圣遗物收集的图标和数据来源于内测游戏客户端的解包，正式服没有解包所以就没更新，等我有时间重新截图再弄这个吧

**Comment by chingkingm** [comment]
这三个的图标我搞好了
链接：https://pan.baidu.com/s/14KxDwL79-gp8R88kVmeKGw 
提取码：h7az

**Comment by H-K-Y** [comment]
好的，我明天看一下

**Comment by chingkingm** [comment]
好，辛苦了

**Comment by H-K-Y** [comment]
圣遗物更新好了
话说你的图标是哪找到的？

**Comment by chingkingm** [comment]
可莉特调-圣遗物评分扒的
