### ISSUE TITLE
3.0须弥地图无法加载

### ISSUE THREAD

**Issue by Cathgao** [H-K-Y/Genshin_Impact_bot#111]
3.0须弥的资源可以搜索，但须弥地图无法加载
![QQ截图20220825190251](https://user-images.githubusercontent.com/21031564/186648119-3f41a744-0674-4603-bdeb-fb2e65e4fe73.png)

**Comment by 1055169799** [comment]
不仅如此，顺带璃月下半部分和稻妻的地图也加载不出了，根据代码返回的图片得知现在是12张地图拼凑在一起的，只加载前三张，也就是蒙德的左边，中间和右边
插件N久没更新，作者没回应，大概是不玩原神了，可惜了这么好一个插件

**Comment by Cathgao** [comment]
> 不仅如此，顺带璃月下半部分和稻妻的地图也加载不出了，根据代码返回的图片得知现在是12张地图拼凑在一起的，只加载前三张，也就是蒙德的左边，中间和右边 插件N久没更新，作者没回应，大概是不玩原神了，可惜了这么好一个插件

genshin.honeyhunterworld.com 这个网站改版了，导致API里的地址都是错的，无法获取新的数据。看有哪位大神能修

**Comment by H-K-Y** [comment]
抽卡图鉴获取的API已经修了。
地图的问题有点难整，因为现在地图太大了，按照原来的代码在低端服务器不好跑了，大改的话太麻烦了，因为工作原因没时间修复了

> > 那样的话，这样顺璃月的下半部分和稻谷也加载不知道，根据返回的图片是12张地图拼凑的，只是加载前三张的，也就是现在带上方块的代码，和右边N久没更新，作者神没有回应插件，大概是不玩原版了，可惜了这么好一个
> 
> genshin.honeyhunterworld.com 这个网站改版了，导致API里的地址都是错的，无法获取新的数据。看有哪位大神能修

**Comment by Cathgao** [comment]
> 抽卡图鉴获取的API已经修了。 地图的问题有点难整，因为现在地图太大了，按照原来的代码在低端服务器不好跑了，大改的话太麻烦了，因为工作原因没时间修复了
> 
> > > 那样的话，这样顺璃月的下半部分和稻谷也加载不知道，根据返回的图片是12张地图拼凑的，只是加载前三张的，也就是现在带上方块的代码，和右边N久没更新，作者神没有回应插件，大概是不玩原版了，可惜了这么好一个
> > 
> > 
> > genshin.honeyhunterworld.com 这个网站改版了，导致API里的地址都是错的，无法获取新的数据。看有哪位大神能修

感谢大佬修复API，我先试试NAS跑不跑的动。还是希望大佬有空的时候能修一下，还是很喜欢这个插件的资源地图

**Comment by H-K-Y** [comment]
> 不仅如此，顺带璃月下半部分和稻妻的地图也加载不出了，根据代码返回的图片得知现在是12张地图拼凑在一起的，只加载前三张，也就是蒙德的左边，中间和右边 插件N久没更新，作者没回应，大概是不玩原神了，可惜了这么好一个插件

地图的问题修好了
