### ISSUE TITLE
[new feature request]可否添加武器角色查询功能？

### ISSUE THREAD

**Issue by cuohua** [H-K-Y/Genshin_Impact_bot#12]
我在 XiaoMiku01/PaimonBot 看到了武器和角色信息查询功能，但是碍于个人能力无法移植。
据悉是调用genshin.minigg.cn的API获取数据，在网站（电脑版）右上角的新版格式/旧版格式可以查看调用数据方法

**Comment by H-K-Y** [comment]
这个功能。。。我感觉不是很必要。。。。。。。。
