### ISSUE TITLE
可莉特调里的抽签能不能移植上来

### ISSUE THREAD

**Issue by aqiu817** [H-K-Y/Genshin_Impact_bot#15]
我们群里翻了一下说想要但是我刷了好久没刷完所有的签河解签所以不知道怎么做

**Comment by H-K-Y** [comment]
我找了找也没找到文本保存在哪里了，应该是把文本加密了

**Comment by H-K-Y** [comment]
我找了找也没找到文本保存在哪里了，应该是把文本加密了

**Comment by wansn05** [comment]
来自6月前的回复....有办法了w![image.png](https://i.loli.net/2021/05/31/UF2uSZBQvqN5bjA.png)

**Comment by wansn05** [comment]
已提交更改
添加了抽签功能，请用如下命令来进行抽签：
`原神抽签` `解签`
详情见 #16
