### ISSUE TITLE
可否添加查询uid的功能？

### ISSUE THREAD

**Issue by KimigaiiWuyi** [H-K-Y/Genshin_Impact_bot#18]
因为隔壁PaimonBot用的是NoneBot2，挂在同一个cqhttp上有点bug，如果能直接添加这个功能那就再好不过了~

**Comment by H-K-Y** [comment]
其实你可以装两个版本的python，一个装NoneBot1跑HoshinoBot，一个装NoneBot2跑PaimonBot，用的端口不一样就行，一个go-cqhttp能对接多个端口的，
查询uid一个账号一天最多查30次，还得搞个账号池，我才懒得做了

**Comment by yimo0908** [comment]
同时使用nb1(hoshinobot)和nb2的话，需要两个python 环境，nb1&amp;2有冲突。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月7日(星期一) 晚上6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [H-K-Y/Genshin_Impact_bot] 可否添加查询uid的功能？ (#18)

**Comment by KimigaiiWuyi** [comment]
> 其实你可以装两个版本的python，一个装NoneBot1跑HoshinoBot，一个装NoneBot2跑PaimonBot，用的端口不一样就行，一个go-cqhttp能对接多个端口的，
> 查询uid一个账号一天最多查30次，还得搞个账号池，我才懒得做了

使用PaimonBot似乎还需要先卸载掉NoneBot1，不然启动报错，我还没有尝试装过两个Python环境，不知道行不行，回头研究一下

**Comment by chingkingm** [comment]
hoshino有查询原神uid的插件：
1. [genshinuid](https://github.com/pcrbot/erinilis-modules/tree/master/genshinuid)，是文字版的，效果为<details><summary>图1</summary>![image.png](https://i.loli.net/2021/06/08/TIYSWJVnZRQGkzK.png)</details>
2. hoshino群文件里的 _原神信息查询_ ，结果更详细，是图片版的，<details><summary>图2</summary>![image.png](https://i.loli.net/2021/06/08/7PYQORshkDI3JpV.png)</details>

**Comment by WansnDev** [comment]
会另外开一个分支做这些不是很必要的附加功能的

**Comment by scofieldle** [comment]
https://github.com/scofieldle/LeoBot/tree/main/hoshino/modules/genshinuid

**Comment by KimigaiiWuyi** [comment]
> 会另外开一个分支做这些不是很必要的附加功能的



> https://github.com/scofieldle/LeoBot/tree/main/hoshino/modules/genshinuid
> 可以参考我的，加了小图，变成转发，拒绝刷屏

我已经自己写了一个插件23333
![-56f5600b80e5b992](https://user-images.githubusercontent.com/55526518/126887981-09b13d87-fd17-4c0a-9e42-d84bfea386a0.png)

**Comment by WansnDev** [comment]
> https://github.com/scofieldle/LeoBot/tree/main/hoshino/modules/genshinuid
> 可以参考我的，加了小图，变成转发，拒绝刷屏

啊这...我还在设计UI...
