### ISSUE TITLE
希望提供.gitignore文件

### ISSUE THREAD

**Issue by maxesisn** [H-K-Y/Genshin_Impact_bot#2]
希望提供.gitignore文件，以忽略插件生成的部分配置文件，如
```
gacha/gid_pool.json
seek_god_eye/uid_info.json
```
以便于维持项目文件的整洁，并使得编辑器的Git插件不会提示有Untracked文件（小声

**Comment by H-K-Y** [comment]
传上来也没用，我的.gitignore文件里啥都没有，我本地电脑都没有机器人，写完代码是推到GitHub再拉到服务器上才跑起来测试的，你说的这两个文件我本地也没有生成
