### ISSUE TITLE
原神抽签文本的绘制位置存在偏差

### ISSUE THREAD

**Issue by N-zi** [H-K-Y/Genshin_Impact_bot#21]
签的类型描述绘制出窗口，时间文本的位置也未居中

**Comment by H-K-Y** [comment]
你试试吧python的Pillow库升级到8.0.0以上

**Comment by WansnDev** [comment]
还不能解决的话可以方便你把截图发一下吗？用[sm.ms](https://sm.ms/)进行上传

**Comment by WansnDev** [comment]
> 还不能解决的话可以方便你把截图发一下吗？用[sm.ms](https://sm.ms/)进行上传

附，hoshino bot的requirements.txt似乎是旧版pillow，你可以运行`pip install pillow --upgrade`进行升级

**Comment by N-zi** [comment]
考虑到其他插件的兼容问题就不升级pillow包了，最后是直接修改文本绘制位置解决的
