### ISSUE TITLE
金苹果群岛资源无法查询

### ISSUE THREAD

**Issue by Mei-Sakura** [H-K-Y/Genshin_Impact_bot#22]
金苹果群岛的新资源无法查询，提示米游社未更新，预计是本地没有地图文件，而且程序无法分辨不同地区。
请更新，谢谢！

**Comment by WansnDev** [comment]
不，其实是因为二者的API是分开的
一个是提瓦特资源一个是金苹果岛

鉴于金苹果岛有**时效性**，~~大概不会加~~在做了在做了

**Comment by WansnDev** [comment]
其实是计划把地图转到[biwiki](https://wiki.biligame.com/ys/)那个的

***附***：要加你说的分辨资源的功能的话大概率会顺便加上智能识别文本 ~~（不过会牺牲掉一点搜索效率~~）~~

**Comment by Mei-Sakura** [comment]
谢谢解答，已经懂了（等着白嫖）

**Comment by WansnDev** [comment]
咳咳，金苹果岛要没了，估计不会做了orz
