### ISSUE TITLE
木材资源位置有误

### ISSUE THREAD

**Issue by N-zi** [H-K-Y/Genshin_Impact_bot#23]
木材的资源位置查询不对，大部分杉木应该是在蒙德城附近，给出的图在晨曦酒庄
顺带问一下2.0版本要出了，有考虑做稻妻部分的点位图吗

**Comment by WansnDev** [comment]
会跟着更新，不用担心

**Comment by WansnDev** [comment]
ps：木材API似乎是米友社提供的，本地不太好改坐标的样子

**Comment by H-K-Y** [comment]
资源位置是米游社的数据抓来的，米游社数据更新了才能同步更新
