### ISSUE TITLE
黄历文字印歪了是什么原理

### ISSUE THREAD

**Issue by NepPure** [H-K-Y/Genshin_Impact_bot#24]
![image](https://user-images.githubusercontent.com/12379907/125381826-2f825600-e3c7-11eb-818c-99432aa5ab66.png)

_(:з」∠)_

**Comment by H-K-Y** [comment]
把python的Pillow库升级到8.0.0以上

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/125382323-1201bc00-e3c8-11eb-91ae-d275ec517244.png)

搞定 蟹蟹大佬
