### ISSUE TITLE
新需求卡池自动更新

### ISSUE THREAD

**Issue by NepPure** [H-K-Y/Genshin_Impact_bot#25]
（饶头.jpg）

**Comment by WansnDev** [comment]
啊 这个想做但是图标就得用回旧的，而不是图鉴内的图
~~（要不从github更新）~~

**Comment by NepPure** [comment]
又能自动又能用图鉴的图，你行的！

**Comment by WansnDev** [comment]
暂时做不了，原因如下

**方案**
1. 爬取米游社
> 米游社观测枢的卡池信息发布url非固定，爬取只能抓取到角色池（武器池 · 神铸赋形不在活动日历内）
> 角色avatar与当前的图鉴图不符
2. 爬取bwiki
> bwiki的首页虽然有完全的信息，但bwiki维护人员为方便，在维护时用标签内直接定义样式的方式来写html样式，爬取时耗时较长；
> bwiki的角色avatar仅有 30 x 30 的 **高清** 画质

解决方案也有，但是比较麻烦

1. 从GitHub同步（对某些VPS不友好）
2. 从bwiki获取卡池，并从国外网站获取完整avatar并拼接（考虑中）

**Comment by smallsay** [comment]
> 暂时做不了，原因如下
> 
> **方案**
> 
> 1. 爬取米游社
> 
> > 米游社观测枢的卡池信息发布url非固定，爬取只能抓取到角色池（武器池 · 神铸赋形不在活动日历内）
> > 角色avatar与当前的图鉴图不符
> 
> 1. 爬取bwiki
> 
> > bwiki的首页虽然有完全的信息，但bwiki维护人员为方便，在维护时用标签内直接定义样式的方式来写html样式，爬取时耗时较长；
> > bwiki的角色avatar仅有 30 x 30 的 **高清** 画质
> 
> 解决方案也有，但是比较麻烦
> 
> 1. 从GitHub同步（对某些VPS不友好）
> 2. 从bwiki获取卡池，并从国外网站获取完整avatar并拼接（考虑中）

我相信dalao你行的！

**Comment by zipated** [comment]
> 暂时做不了，原因如下
> 
> **方案**
> 
> 1. 爬取米游社
> 
> > 米游社观测枢的卡池信息发布url非固定，爬取只能抓取到角色池（武器池 · 神铸赋形不在活动日历内）
> > 角色avatar与当前的图鉴图不符
> 
> 1. 爬取bwiki
> 
> > bwiki的首页虽然有完全的信息，但bwiki维护人员为方便，在维护时用标签内直接定义样式的方式来写html样式，爬取时耗时较长；
> > bwiki的角色avatar仅有 30 x 30 的 **高清** 画质
> 
> 解决方案也有，但是比较麻烦
> 
> 1. 从GitHub同步（对某些VPS不友好）
> 2. 从bwiki获取卡池，并从国外网站获取完整avatar并拼接（考虑中）

不打算用gitee吗）

**Comment by xi-yue-233** [comment]
这个网站貌似有原神真的十连抽卡图的图片，角色、武器都有，而且访问不需要翻墙，可以考虑从bwiki上筛选出祈愿的武器和角色然后按照名字进行爬取，把抽卡图爬下来，应该可以做出最还原原神抽卡图的想法了
https://genshin.honeyhunterworld.com/db/char/characters/?lang=CHS

**Comment by WansnDev** [comment]
> 这个网站貌似有原神真的十连抽卡图的图片，角色、武器都有，而且访问不需要翻墙，可以考虑从bwiki上筛选出祈愿的武器和角色然后按照名字进行爬取，把抽卡图爬下来，应该可以做出最还原原神抽卡图的想法了
> https://genshin.honeyhunterworld.com/db/char/characters/?lang=CHS

这个知道，甚至官网就有高清立绘，但真要做的话缺抽卡ui的素材
（昨天抽雷神忘了截图做素材了
~~其实我还是更希望有原版的素材而非自行抠图的，**力求完美**~~

**Comment by xi-yue-233** [comment]
> > 这个网站貌似有原神真的十连抽卡图的图片，角色、武器都有，而且访问不需要翻墙，可以考虑从bwiki上筛选出祈愿的武器和角色然后按照名字进行爬取，把抽卡图爬下来，应该可以做出最还原原神抽卡图的想法了
> > https://genshin.honeyhunterworld.com/db/char/characters/?lang=CHS
> 
> 这个知道，甚至官网就有高清立绘，但真要做的话缺抽卡ui的素材
> （昨天抽雷神忘了截图做素材了
> ~其实我还是更希望有原版的素材而非自行抠图的，**力求完美**~
不不不你可能没太懂我的意思，这个网站就是有抽卡十连图的素材，甚至武器的也有，只需要把一张抽卡图的底图掏出来就可以获得底图素材，然后用pillow库将这个网站上的gacha image合成上去就行了，至于要爬出特定的祈愿武器可以从bwiki上筛选出来
![1632140111(1)](https://user-images.githubusercontent.com/58218656/134000546-fbc93c20-e590-433b-b372-2e84a836d02e.png)
![1632140222(1)](https://user-images.githubusercontent.com/58218656/134000787-23e02f52-21b1-4711-a634-c588021858c5.png)
就是说可以直接合成出原神里面的这种抽卡图
![image](https://user-images.githubusercontent.com/58218656/134001166-f6e6be16-9471-4f0f-8e4b-2c2155d1f01f.png)

**Comment by xi-yue-233** [comment]
我现在已经可以通过这个https://genshin.honeyhunterworld.com/自动进行爬虫抽卡图的获取了，但是bwiki我还在尝试着爬下来

**Comment by H-K-Y** [comment]
这个项目的抽卡有90连抽和180连抽，所以本来就不想还原游戏的画面
自动更新这个问题，准备爬B站的卡池内容 + 内鬼网的图片数据，等有时间在做吧

**Comment by H-K-Y** [comment]
卡池自动更新完成了，git pull吧
