### ISSUE TITLE
稻妻资源查询killed

### ISSUE THREAD

**Issue by KimigaiiWuyi** [H-K-Y/Genshin_Impact_bot#29]
![2D@TSV%F ZNE)7 5CT)4 C](https://user-images.githubusercontent.com/55526518/126888570-c235a6f2-0bda-4e7d-a9c8-3a1095f3c74c.png)

**Comment by H-K-Y** [comment]
![QQ截图20210725172603](https://user-images.githubusercontent.com/33424676/126894357-845ce3e2-e057-48b4-910e-0c0438c514af.png)
我测试了一下没有问题，可能是你服务器的问题

**Comment by KimigaiiWuyi** [comment]
> ![QQ截图20210725172603](https://user-images.githubusercontent.com/33424676/126894357-845ce3e2-e057-48b4-910e-0c0438c514af.png)
> 我测试了一下没有问题，可能是你服务器的问题

其他功能都正常，就资源查询有问题，之前是没有问题的，我就git pull更新了一下
cqhttp那里显示
![Snipaste_2021-07-25_18-09-57](https://user-images.githubusercontent.com/55526518/126895505-fbf6186f-af61-4e1d-9193-e41e6e9ef2f0.png)
这大概会是什么原因造成的呢？

**Comment by H-K-Y** [comment]
你服务器什么配置的，资源查询使用的时候很多次图像处理和读取，如果服务器配置太低的话可能会出现killed

**Comment by H-K-Y** [comment]
我把资源查询的代码逻辑调整了一下，你git pull一下再试试资源查询

**Comment by KimigaiiWuyi** [comment]
> 我把资源查询的代码逻辑调整了一下，你git pull一下再试试资源查询

可以了，正常运行，虽然会报警告，感谢！
![Snipaste_2021-07-27_20-56-29](https://user-images.githubusercontent.com/55526518/127157310-64caa651-9720-4aa4-bf6c-bce9eb3f4fd8.png)

**Comment by H-K-Y** [comment]
这个警告不用管，Image在读取大文件会自动报这个警告
