### ISSUE TITLE
一个错误提示，不确定是否有影响

### ISSUE THREAD

**Issue by DavidYin166** [H-K-Y/Genshin_Impact_bot#30]
[2021-07-31 16:51:10,938 nonebot] INFO: Succeeded to import "hoshino.modules.Genshin_Impact_bot-main.almanac"
/root/.cache/pypoetry/virtualenvs/pcrbot-k99M20cq-py3.9/lib/python3.9/site-packages/PIL/Image.py:2855: DecompressionBombWarning: Image size (150994944 pixels
) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

**Comment by H-K-Y** [comment]
不用管，Image读取大的图片文件就会报这个警告
