### ISSUE TITLE
我尽力了，可我实在找不到

### ISSUE THREAD

**Issue by DavidYin166** [H-K-Y/Genshin_Impact_bot#32]
非常抱歉，这样提交一个issue似乎是不合适的，但是，我搜遍了google和baidu，结果只有漫天盖地的广告和公众号，实在是没有找到和项目仓库里武器、人物图鉴风格一致的资料网。
我没办法了，实在抱歉，只能来伸手了，请问，项目里的人物、武器图鉴是从哪里抓取的？

**Comment by H-K-Y** [comment]
啊这，就是游戏里的角色图鉴截图。。。。。。。

**Comment by DavidYin166** [comment]
啊，这，原来是这样的吗，虽然，一开始也有想到过这一点...
不过有个问题就是，没解锁的角色和武器是灰色的这个该怎么办呢？
对了，顺便一提，可否告诉一下您的游戏分辨率？我用1920x1200的屏幕，图鉴图标无法达到130x160，只能放大，但是这样图标会虚...

**Comment by H-K-Y** [comment]
我截图用的是1920×1080分辨率，没开图鉴的就找朋友截图，或者截完图在图片处理的软件里调色调亮装作自己开图鉴了

**Comment by DavidYin166** [comment]
原来如此。
非常感谢您的解答！
