### ISSUE TITLE
资源位置显示坐标有明显异常

### ISSUE THREAD

**Issue by Gaylone** [H-K-Y/Genshin_Impact_bot#37]
在查询任意资源位置时返回的地图坐标中，坐标明显整体偏移，如图
![QQ图片20210902135817](https://user-images.githubusercontent.com/69965504/131789927-60d7f43a-b4c2-43e9-a8f1-cd4fb20d112f.jpg)
![QQ图片20210902135824](https://user-images.githubusercontent.com/69965504/131789934-75633d56-3606-4ad9-96be-b717a6d92b5d.jpg)

**Comment by WansnDev** [comment]
请检查你的pillow版本。


请使用如下命令来检查：```pip show pillow```;

***我该如何更新？***：
使用```pip install pillow --upgrade```
或```pip install pillow==8.2.0```来进行更新.

**Comment by Gaylone** [comment]
pillow版本8.2.0
![`OJTW} 0O@}}B__Q )I C 7](https://user-images.githubusercontent.com/69965504/131792048-806160c7-f026-4e7a-b016-dded7fa5c5d0.png)
重启后仍然偏移
![QQ图片20210902141214](https://user-images.githubusercontent.com/69965504/131792084-5f6190d9-dc36-4c95-b126-a75f944b614b.jpg)

**Comment by H-K-Y** [comment]
你试试git pull一下最新的版本
然后群里发送更新原神地图
再试一下

**Comment by Gaylone** [comment]
没有检测到你的更新

**Comment by H-K-Y** [comment]
我知道，我只是想让你拉一下最新的版本，
你用的HoshinoBot版的还是nonebot2版的？

**Comment by Gaylone** [comment]
hoshino

**Comment by Gaylone** [comment]
唉 发送更新原神地图就好了
