### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by aqiu817** [H-K-Y/Genshin_Impact_bot#4]
1.切换卡池是否也能加入机器人管理员限定，避免群友疯狂换卡池（我已经挨这样了）
2.刷副本可以使用更常用的名字例如火本雷本岩本等等

**Comment by aqiu817** [comment]
再补一个（
如果可以刷无相/树更好了

**Comment by H-K-Y** [comment]
更新了，现在切换卡池只限机器人管理和QQ群管理使用，
副本的名称也改了，不过目前没有岩套的图标所以还没有加入岩本
无相boss和冰火树掉落圣遗物和龙狼是一样的就没有单独加
