### ISSUE TITLE
目前资源查询插件反应较慢

### ISSUE THREAD

**Issue by scofieldle** [H-K-Y/Genshin_Impact_bot#44]
不知道是地图较大还是paste图标耗时太长，现在使用资源查询功能经常会卡住机器人其他功能很久。怎么可以利用async、await让该功能不影响其他功能响应，以及怎么更快paste一大堆图标。。

**Comment by H-K-Y** [comment]
机器人不同的功能是相互独立的，一个操作卡住不会影响其他功能吧
现在资源查询反应慢是因为地图文件太大了，而且考虑到插件有可能在低端服务器运行数据没有常驻内存，不然有可能出现killed
地图这一块我会想办法缩小点减少大小，读取的IO操作会加上async，但是paste这类操作加上async应该是没用的

**Comment by H-K-Y** [comment]
更新了，你git pull 试一下
