### ISSUE TITLE
原神黄历查看不了

### ISSUE THREAD

**Issue by xiguadoudou** [H-K-Y/Genshin_Impact_bot#48]
我用nonebot2插件，输入元神黄历不理我

运行nonebot2提示这个with open(os.path.join(FILE_PATH, LIST_PATH), 'r', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'src/plugins/Genshin_Imp
act_bot\\almanac\\src/plugins/Genshin_Impact_bot\\almanac\\assets\\almanac_list.
json'

**Comment by H-K-Y** [comment]
报错信息发完整了，信息太少看不出来

**Comment by xiguadoudou** [comment]
![Uploading UQEH]QNGUOUC7`1O_(YSK25.png…]()

**Comment by xiguadoudou** [comment]
![qxlarge-dsc-996C1BF3E3FD4FC1E071A54F7835E1E6](https://user-images.githubusercontent.com/89190859/133070048-0d76d717-927c-473a-a0df-09558e20f536.jpg)

**Comment by H-K-Y** [comment]
上边应该还有报错信息吧

**Comment by xiguadoudou** [comment]
![2fb42e7cd2207afc](https://user-images.githubusercontent.com/89190859/133070728-86165575-8bae-46ab-8dc5-f828382a0279.png)

**Comment by H-K-Y** [comment]
修复了，git pull更新一下就行

**Comment by xiguadoudou** [comment]
好了，感谢大佬
