### ISSUE TITLE
1.1更新相关

### ISSUE THREAD

**Issue by yimo0908** [H-K-Y/Genshin_Impact_bot#5]
1. `怪物（精英）`& `怪物（普通）`可以直接从游戏里的`冒险之证`进行跟踪，可以去掉这两项。
2. patch1.1增加特殊怪物`大伟丘`，可加进bot资源列表
3. patch1.1增加区域特产`竹笋`、`鳅鳅宝玉`和矿产`魔晶矿`

**Comment by H-K-Y** [comment]
特产和地点是从米游社的的地图那抓来的，一开始我写成了数据保存在本地所以没有更新，等我有时间重写一下吧，改成和米游社地图同步更新的

**Comment by H-K-Y** [comment]
数据改成自动更新了，你git pull一下吧
