### ISSUE TITLE
原神黄历没有新增的内容了

### ISSUE THREAD

**Issue by silhoues** [H-K-Y/Genshin_Impact_bot#54]
可莉特调的原神黄历有了新内容，想帮忙更新但是不知道去哪找json文件

**Comment by silhoues** [comment]
观察了2天，可能是可莉特调修改了黄历的蚊子内容，所以跟现在的看一起来不一致了
![image](https://user-images.githubusercontent.com/91514215/135373080-ff4cd2f8-f27d-4c4a-84a1-130f523ba113.png)

**Comment by H-K-Y** [comment]
我查了一下实际上是部分文本出现了变动，并没有更新很多，没必要去改了
