### ISSUE TITLE
抽卡插件获取图标速度过慢导致插件未被加载

### ISSUE THREAD

**Issue by KazuhaKun** [H-K-Y/Genshin_Impact_bot#58]
模块所采用的更新卡池图标的网站genshin.honeyhunterworld.com在部分地区访问过慢，导致抽卡模块无法被载入。

**Comment by H-K-Y** [comment]
发一下报错日志，是因为访问速度太慢超时了还是什么原因？

**Comment by H-K-Y** [comment]
尝试修了一下，你可以试试

**Comment by KazuhaKun** [comment]
好的

**Comment by Edvision** [comment]
感谢~ 其实不是第一次用的话，更新个别图标应该问题不大。我这边因为迁移了服务器重新拉了代码。后面我自己调timeout到60就下载完了。
