### ISSUE TITLE
[BUG] 更新卡池命令导致卡池数据重复

### ISSUE THREAD

**Issue by niceRAM** [H-K-Y/Genshin_Impact_bot#61]
更新完会自动爬取卡池数据，一切正常。
群里试了试抽卡、又~手贱~强迫症指令更新了一次数据，发现不太对劲，果断又试了一次，就有了如下图场景……
卡池的数据每更新一次都会重复一次，大佬你初始化卡池忘记初始化 `POOL` 了啊 (ˉ▽ˉ；)...

https://github.com/H-K-Y/Genshin_Impact_bot/blob/d861ddec09f0751fe5f9eb0b28b9ec2ad9466d71/gacha/pool_data.py#L261-L277

没细看，目测是 272 这行直接 append 的缘故。
https://github.com/H-K-Y/Genshin_Impact_bot/blob/d861ddec09f0751fe5f9eb0b28b9ec2ad9466d71/gacha/pool_data.py#L272

* 截图有点长，github 可能显示不全，[这个是截图直链](https://c2cpicdw.qpic.cn/offpic_new/0/0-10000-849B40828AAD190F27D89CB373FA021A/0)
![更新卡池命令导致卡池数据重复](https://c2cpicdw.qpic.cn/offpic_new/0/0-10000-849B40828AAD190F27D89CB373FA021A/0)

**Comment by H-K-Y** [comment]
艹，更新的时候忘了删原来的数据了
