### ISSUE TITLE
bot好像不支持好友聊天(nonebot)

### ISSUE THREAD

**Issue by SunShineJF** [H-K-Y/Genshin_Impact_bot#65]
今天折腾了一天，bot正常运行，发现bot部分指令不支持好友聊天 。
好友聊天中，指令中抽卡相关指令都无法正常回复。
后来想到该插件是群bot，单独建群后问题解决。

之后有望加入单聊回复功能吗？

**Comment by H-K-Y** [comment]
哦，我写的时候没考虑到私聊使用

**Comment by SunShineJF** [comment]
我临时创了个群，可以正常使用了。但是群里就两人0.0。
之后有打算完善此功能吗？
