### ISSUE TITLE
卡池信息出错，hoshino版本

### ISSUE THREAD

**Issue by chingkingm** [H-K-Y/Genshin_Impact_bot#69]
卡池 [API](https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/gacha/list.json) 同时返回了两期祈愿的数据，导致卡池信息出错
![Snipaste_2021-11-01_19-53-51](https://user-images.githubusercontent.com/17588900/139667537-2d3813df-288b-4a50-b3c5-5dee7fdd2040.png)

**Comment by H-K-Y** [comment]
修好了
