### ISSUE TITLE
请问静态资源该去哪里找

### ISSUE THREAD

**Issue by var-mixer** [H-K-Y/Genshin_Impact_bot#7]
想问下角色头像等静态资源都是从哪里收集的呢，在bwiki上爬下来的图片不是金色背景的，在原神官方wiki的也是白色背景。

**Comment by H-K-Y** [comment]
原神官网上有带透明通道的角色的头像，在这个页面 https://ys.mihoyo.com/main/character/mondstadt?char=0
人物的金色背景和星星是我自己加的
武器应该是游戏的截图和米游社观测枢爬下来的

**Comment by var-mixer** [comment]
谢谢大佬回复
