### ISSUE TITLE
群消息发送失败，账号可能被风控

### ISSUE THREAD

**Issue by WenZhenLin1** [H-K-Y/Genshin_Impact_bot#84]
大佬你好，程序运行几个小时之后会发生bot无法正常回复群消息，但可以正常回复个人私信，后台日志里显示这条“群消息发送失败，账号可能被风控”。大佬有遇到这个情况吗？是不是qq有需要改动的设置？

**Comment by Wansn-w** [comment]
可能你挂bot的账号是新号或者因为一些其他原因被风控了 比如举报之类，**和本项目无关**哒~

**解决方法**
1. 更换QQ号
2. 更新 go-cqhttp客户端
3. 正常使用几天挂bot的QQ号

**Comment by MinNanR** [comment]
> 挂几天QQ号意思是用go-cqhttp登录然后等几天再测还是说要用手机或者电脑登录QQ？
