### ISSUE TITLE
一键安装脚本里的gocqhttp超时导致容器被停止

### ISSUE THREAD

**Issue by YD-Cat** [H-K-Y/Genshin_Impact_bot#88]
使用一键安装脚本安装Hoshino
安装完后其他两个容器都正常，就gocqhttp启动后，过了一会超时报错，然后gocqhttp容器自动停止
重启容器也是一样
![image](https://user-images.githubusercontent.com/61802497/148714739-042ec33c-9e3c-495d-97ac-60b93017f54f.png)

**Comment by MingxuanGame** [comment]
请尝试更新go-cqhttp

**Comment by MingxuanGame** [comment]
##### 1.从**[Mrs4s/go-cqhttp](https://github.com/Mrs4s/go-cqhttp)**的Release下载`go-cqhttp_linux_amd64.tar.gz`

```shell
curl -O https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.0-beta8-fix2/go-cqhttp_linux_amd64.tar.gz
```

##### 2.解压

```shell
tar xf go-cqhttp_linux_amd64.tar.gz
```

##### 3.复制go-cqhttp到容器

```shell
docker cp go-cqhttp gocqhttp:/usr/bin/cqhttp
```

##### 4.修改配置文件

输入下面的命令启动go-cqhttp容器并进入容器命令行

**警告：退出容器命令行需按Ctrl-p，Ctrl-q组合键**

```shell
docker start gocqhttp  # 启动容器
docker attach gocqhttp  # 进入容器命令行
# 如果慢可以使用下面的组合命令
docker start gocqhttp && docker attach gocqhttp
```

你的终端输出应该是空白（我的是这样），直接输入`3`（反向 Websocket 通信）回车

然后修改配置文件`你执行安装脚本的位置/gocqhttp_data/config.yml`

将第4行`uin`修改成机器人的QQ号

将第5行`password`修改成机器人的密码（单引号不要删）

将第96行`universal`修改成`ws://hoshino:8080/ws/`

##### 5.机器人验证

输入上一步的打开并进入容器的命令，依照说明完成即可

**Comment by MingxuanGame** [comment]
> 感谢大佬，不过还需要按照旧配置文件把access_token加上才能正常的连接到hoshino 但我发现我这边有些命令发送后没有任何效果 ![image](https://user-images.githubusercontent.com/61802497/148798359-10bb1eb8-408b-4339-92f8-0bc76cb4d88d.png)

请发送hoshino的log信息和go-cqhttp的信息（保护隐私，可以对QQ号群号等信息进行删减，注明机器人和发送者即可）

**Comment by YD-Cat** [comment]
> > 感谢大佬，不过还需要按照旧配置文件把access_token加上才能正常的连接到hoshino 但我发现我这边有些命令发送后没有任何效果 ![image](https://user-images.githubusercontent.com/61802497/148798359-10bb1eb8-408b-4339-92f8-0bc76cb4d88d.png)
> 
> 请发送hoshino的log信息和go-cqhttp的信息（保护隐私，可以对QQ号群号等信息进行删减，注明机器人和发送者即可）

hoshino和gocqhttp控制台输出没什么问题
![hoshino](https://user-images.githubusercontent.com/61802497/148864160-e38d6b7c-8110-41c4-ab47-4e6c977c0f7e.png)
![gocqhttp](https://user-images.githubusercontent.com/61802497/148864170-7fc345d7-4716-4e66-8424-198b3eda135e.png)

目前发现有如下问题：

1. hoshino错误日志显示无法导入loguru模块（图1）
查看了下python已安装的模块，是有loguru的，自行在python里也是能导入的（图2图3）
2. nonebot模块没能正常安装，安装requirements.txt有如下报错，试了好几个安装源都有一样的报错（图3图4）

![hoshino error](https://user-images.githubusercontent.com/61802497/148865296-4561304a-4ae6-479e-a2dc-70f025e34d02.png)
![import loguru](https://user-images.githubusercontent.com/61802497/148865491-c5fd9b67-4bfb-4a8b-b3be-e6600f8eeefb.png)
![pip list](https://user-images.githubusercontent.com/61802497/148866060-f160bd2c-abc7-4b39-be73-f2b39f05cd5f.png)
![install nonebot](https://user-images.githubusercontent.com/61802497/148865911-8cd44ec3-395e-4f68-a430-33babeb0f570.png)

**Comment by MingxuanGame** [comment]
> hoshino和gocqhttp控制台输出没什么问题 ![hoshino](https://user-images.githubusercontent.com/61802497/148864160-e38d6b7c-8110-41c4-ab47-4e6c977c0f7e.png) ![gocqhttp](https://user-images.githubusercontent.com/61802497/148864170-7fc345d7-4716-4e66-8424-198b3eda135e.png)
> 
> 目前发现有如下问题：
> 
> 1. hoshino错误日志显示无法导入loguru模块（图1）
>    查看了下python已安装的模块，是有loguru的，自行在python里也是能导入的（图2图3）
> 2. nonebot模块没能正常安装，安装requirements.txt有如下报错，试了好几个安装源都有一样的报错（图3图4）
> 
> ![hoshino error](https://user-images.githubusercontent.com/61802497/148865296-4561304a-4ae6-479e-a2dc-70f025e34d02.png) ![import loguru](https://user-images.githubusercontent.com/61802497/148865491-c5fd9b67-4bfb-4a8b-b3be-e6600f8eeefb.png) ![pip list](https://user-images.githubusercontent.com/61802497/148866060-f160bd2c-abc7-4b39-be73-f2b39f05cd5f.png) ![install nonebot](https://user-images.githubusercontent.com/61802497/148865911-8cd44ec3-395e-4f68-a430-33babeb0f570.png)

尝试使用`python3 -m pip install`安装需要的模块
