### ISSUE TITLE
原神资源列表命令报错

### ISSUE THREAD

**Issue by BOSSzz** [H-K-Y/Genshin_Impact_bot#9]
mirai端报错：
E/OneBot: 未知OneBot API: send_group_forward_msg

**Comment by H-K-Y** [comment]
OneBot似乎没有发送转发消息的api
你可以试试把 query_resource_points/__init__.py 里边34行的 await bot.send(ev, get_resource_list_mes(), at_sender=True) 的注释去掉
然后把35行 await bot.send_group_forward_msg(group_id=ev['group_id'], messages=mes_list) 注释，不过这么做的话这条消息太长了有可能发送不出去

**Comment by BOSSzz** [comment]
> OneBot似乎没有发送转发消息的api
> 你可以试试把 query_resource_points/**init**.py 里边34行的 await bot.send(ev, get_resource_list_mes(), at_sender=True) 的注释去掉
> 然后把35行 await bot.send_group_forward_msg(group_id=ev['group_id'], messages=mes_list) 注释，不过这么做的话这条消息太长了有可能发送不出去

ok，先这样试试，希望onebot以后能支持转发消息
