### ISSUE TITLE
需要更新一波渊下宫地图

### ISSUE THREAD

**Issue by DaiShengSheng** [H-K-Y/Genshin_Impact_bot#90]
米游社wiki更了渊下宫的地图，正常更新地图的命令拉不出来渊下宫的图
现在查渊下宫内的资源会直接报错

**Comment by Wansn-w** [comment]
嗯 在做了 而且之后会把原来的返回图片+文字的形式改为纯图片，UI已经好了其实![6de785ada7d8f518.png](https://user-images.githubusercontent.com/49867372/150639726-006f2369-e6a8-403e-af00-8d73b68b4b43.png)

**Comment by Wansn-w** [comment]
届时可以通过长按识别二维码以访问网页版大地图，点位也将是你所查询的那些

**Comment by DaiShengSheng** [comment]
彳亍！

**Comment by Wansn-w** [comment]
> 彳亍！

圆角难度其实有点大（主要是原图可能4k甚至更高，如甜甜花就是16k的

**Comment by Wansn-w** [comment]
将在GI Bot 2.0中实现 敬请期待(咕咕咕

**Comment by DaiShengSheng** [comment]
彳亍，等你的鸽子熟

**Comment by Wansn-w** [comment]
加个群一起讨论 https://jq.qq.com/?_wv=1027&k=1faV2txy

**Comment by NepPure** [comment]
666支持一波

**Comment by Wansn-w** [comment]
#120
