### ISSUE TITLE
请问这个适配nonebotv2.0.0b1了吗

### ISSUE THREAD

**Issue by zhadsa** [H-K-Y/Genshin_Impact_bot#94]

**Comment by MingxuanGame** [comment]
目前未对nonebot 2.0.0b1的支持

请继续使用2.0.0a16版本（适配器:cqhttp 2.0.0a16）

```shell
python3 -m pip install nomebot==2.0.0a16 nonebot-adapter-cqhttp==2.0.0a16
```

**Comment by zhadsa** [comment]
好，谢谢

> 目前未支持nonebot 2.0.0b1
> 
> 请继续使用2.0.0a16版本（适配器:cqhttp 2.0.0a16）
> 
> ```shell
> python3 -m pip install nonebot==2.0.0a16 nonebot-adapter-cqhttp==2.0.0a16
> ```

**Comment by zhadsa** [comment]
好，谢谢
